copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Ani leDodi. Ct 6,3 ; 7,12.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Ani ma'amin. Varshever Geto-Lid.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Ashre ha-ish. Ps 1,1-2.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Av ha-rahaman. Da 9,18-19.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Barukh Elohenu.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Barukh ha-Maqom.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Betset Israël. Ps 114.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "ehad mi yodea . Comptine.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Hashivenu eleïkha.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Hinneh lo yanum. Ps 121,1.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Hinneh mah tov.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Kol ha-'olam kullo. N. de Braslaw.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Lekhah Dodi. Accueil du Shabbat.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Lomir allen. A glazele vaijn.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Lou Yehi. Naomi Shemer.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Ma'oz Tsour yeshouati (Paroles).pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Mi ha-ish. Ps 34,13-15.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Min ha-metsar. Ps 118,5-6.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Od Yishama. Jr b33,10-11.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Oyfn pripetschik RV.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Qol Dodi. Ct 2,8.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Ronni we-simhi. Za 2,14.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Shema Yisrael. De 6,4.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Sim shalom.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Wihuda le-olam teshev. Jl 4,20.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Yedid Nephesh.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Yepheh noph. cf.Ps 48,3.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Yerushalayim shel zahav. Naomi Shemer.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Yevarekhekha hashem mi-Sion. Ps 128,5-6.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" "Zekhor davar. Ps 119,49-51 RV.pdf"
copy "C:\SiteGITHUB\hebreu\complements\EnTravaux.pdf" ".pdf"